# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4bc36cc27fb4de18312d23c1457cdaeec3ad9bbd3b759921a2ba496123c7382067831bf55a65ebb730fc175b67b8722312aca3fc8d67df1bf98ed432c112d61b

test:
  secret_key_base: 8376b61ddaaed22fba73b216cd2c7dcde4c0159001aa1aefa176789f9a1102a4584a38784a47b57a2bc97d279545c2e3ba1d25be860be713a3eb69ec6fba053f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
